### ISSUE TITLE
How to set location?

### ISSUE THREAD

**Issue by Voluntaryism** [tranhungt/tinder_pro#3]
The location is set by default to the last login location on Tinder, so how do you override it to set the location for a latitude and longitude?

**Comment by tranhungt** [comment]
Hi @Voluntaryism ,
Great question.
You can set your location via this method:

.update_location(latitude, longitude, callback)
Updates your current position. Latitude and longitude are float precision.

What I like to do is go on google maps, click on a point, and it will give you a latitude-longitude, and then just use that. :)

Let me know if that helps.

Remember to star the repo, so we can all share the love.

**Comment by Voluntaryism** [comment]
Starred. Thanks for the response :)

**Comment by tranhungt** [comment]
Cool man. Thanks!
Let me know if you have any other questions or suggestions. Feel free to
post on the issues board or send a pull request for any changes.

Thanks again.
